name = "fishtank-edge"
main = "src/index.ts"
compatibility_date = "2026-05-20"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WORLD_ROOM"
class_name = "WorldRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WorldRoom"]
